### PR TITLE
Define Connector API

### PR DESCRIPTION
**Pull request by mLuby**
# ⚠️  Breaking API change!
- [x] Expose public methods only.
- [x] Remove sync methods.
- [x] Make `getResultRowForPixel` take a single callback. (It still accepts an array of callbacks but warns that's deprecated.)
- [x] Drop "*Async" method suffix (since everything's async now).
- [x] Everything uses node-style callbacks. (Promises [not supported in IE11](https://caniuse.com/#search=promises).)
- [x] clean up JSDocs
- [x] Add integration tests for _all_ public methods (except side-effect-ful ones for now).
- [x] Remove multiplexing. (It's never used and makes the code complex).

# 🅿️ Public methods
```
connect
createFrontendView
createLink
createTable
dbName
deleteFrontendView
detectColumnTypes
disconnect
getFields
getFrontendView
getFrontendViews
getLinkView
getPixel
getServerStatus
getTables
host
logging
password
port
protocol
query
renderVega
sessionId
user
validateQuery
```

### CODE REVIEW

**Comment by mLuby** [comment]
retest this please

**Comment by Drecula** [comment]
In Immerse, createFrontendView() appears to only be called for saving a dashboard. If this is true, then I suggest we rename it saveDashboard(), saveChartCollection(), or something else more precise/semantic.

**Comment by nytai** [comment]
If we are going with above approach, we should rename all instances of FrontendView to Dashboard. I'd be wary of introducing breaking changes. Might be better to still maintain previous methods as aliases to renamed methods, and issue a warnings when they are called.

**Comment by mLuby** [comment]
@nytai there's currently a confusing mix of promise and callback-style functions. Since making that consistent means breaking the current API, I figure we should do our renaming now as well (and ditch those `funcNameAsync` names—doesn't even tell you if it's a promise, async, or what…

**Pull request merged**
