### PR TITLE
WIP micah/52 get completion hints

### PR DESCRIPTION
**Pull request by micahstubbs**
will make a PR to see the diff.  still very WIP.

gh issue https://github.com/mapd/mapd-connector/issues/52

### Tasks to Merge 🚢 

- [ ] get a code review from @biovisualize or @clhenrick 
- [ ] merge master in, resolve conflicts
- [ ] remove old commented code
- [ ] remove logging

### CODE REVIEW

**Comment by micahstubbs** [comment]
progress! can now see the `getCompletionHints` function on the `services.get('MapdCon')` object in the browser  

getcompletionhints-1

**Comment by clhenrick** [comment]
@micahstubbs it might be good to sync up with @andrewseidl on this PR so that we can get it into master. Andrew has another PR that includes thrift updates, so we want to resolve any merge conflicts.

**Comment by clhenrick** [comment]
@micahstubbs it might be good to sync up with @andrewseidl on this PR so that we can get it into master. Andrew has another PR that includes thrift updates, so we want to resolve any merge conflicts.

**Comment by andrewseidl** [comment]
My PR simply has the auto-generated Thrift updates, which we can re-generate once this PR is merged.

**Comment by clhenrick** [comment]
@nytai I'm seeing the following error in the SQL editor:

```
sql-editor-action-creators.js?2b53:162 Uncaught TypeError: services.get(...).getCompletionHints is not a function
    at SQLEditorGetCompletionHintsThunk (sql-editor-action-creators.js?2b53:162)
    at eval (index.js?e2e7:11)
    at eval (middleware.js?8078:66)
    at Object.eval [as dispatch] (middleware.js?416a:22)
    at dispatch (<anonymous>:1:27776)
    at Object.getCompletionHints (sql-editor-parent.js?9537:132)
    at SqlEditorInput.__onBeforeChange__REACT_HOT_LOADER__ (sql-editor-input.js?82b6:281)
    at SqlEditorInput.__onBeforeChange__REACT_HOT_LOADER__ (createPrototypeProxy.js?6ea8:44)
    at SqlEditorInput._this.onBeforeChange (sql-editor-input.js?82b6:51)
    at complete (debounce.js?3b82:101)
```

**Pull request merged**
